---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags: aptupdate
  become: yes

- name: Installing the required apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - supervisor
    - postgresql
    - postgresql-contrib
    - git
    - python3-pip
    - python3-venv
    - python-psycopg2
  tags: installpkgs
  become: yes

- name: Starting the nginx,supervisor is state is to be enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - nginx
  - supervisor
  tags: installpkgs
  become: yes
