---
- name: shell command to activate pythonenv
  become_user: "{{ user_name }}" 
  shell: python3 -m venv venv
  become: yes 
  args:
    chdir: "{{ user_homedir }}"
  tags: createvenv

- name: pip cmd
  become_user: "{{ user_name }}"
  pip:
    requirements: "{{ user_homedir }}/requirements.txt"
    virtualenv: "{{ user_homedir }}/venv"
    virtualenv_python: python3
  tags: piprequirements

- name: django migrations
  become_user: "{{ user_name }}"
  django_manage:
    app_path: "{{ user_homedir}}/sampleproject"
    command: migrate
    virtualenv: "{{ user_homedir }}/venv"
  tags: djangomigrations

- name: django collect
  become_user: "{{ user_name }}"
  django_manage:
    app_path: "{{ user_homedir }}/sampleproject"
    command: collectstatic
    link: yes
    virtualenv: "{{ user_homedir }}/venv"
  tags: djangomigrations

